
name: Build and run unit/UI test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-run-unit-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository on the machine
      uses: actions/checkout@v4
    - name: Use Node.js version 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install the dependancies
      run: npm install
    - name: Run Unit tests
      run: npm run test:unit
    - name: Display SoftUni username
      run: echo "vasilsl"

  build-and-run-ui-tests:
    runs-on: ubuntu-latest
    needs: build-and-run-unit-tests

    steps:
    - name: Checkout repository on the machine
      uses: actions/checkout@v4
    - name: Use Node.js version 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install the dependancies
      run: npm install
    - name: Install playwright browsers
      run: npx playwright install
    - name: Start the application
      run: npm start &
    - name: Run ui tests
      run: npm run test:ui