
name: Build and run UI test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository on the machine
      uses: actions/checkout@v3
    - name: Use Node.js version 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install the dependancies
      run: npm install
    - name: Run UI tests
      run: npm run test:ui
